In [2]:
x=5

In [3]:
x

5

In [4]:
x+2

7

In [ ]:
x-2

3

In [ ]:
x*2

10

In [ ]:
x**2

25

In [ ]:
x%2

1

In [ ]:
x/float(2)

2.5

In [ ]:
a = '5,'
b = '3.45,'
c = 'True'
d = a + b + c
print(d)
print(type(d))

5,3.45,True
<class 'str'>


In [ ]:
a = 5 
b = 3 
c = 1
print(a,b,c)
print(type(a))



5 3 1
<class 'int'>


In [ ]:
a = float(5.0)
b = float(1.0)
print(a,b)
print(type(a))

5.0 1.0
<class 'float'>


In [ ]:
a = True
b = True
c = True
print(a,b,c)
print(type(a))


True True True
<class 'bool'>


In [ ]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

In [ ]:
my_string = 'thisStringIsAwesome'
my_string


'thisStringIsAwesome'

In [ ]:
my_string * 2

'thisStringIsAwesomethisStringIsAwesome'

In [ ]:
my_string + 'Innit'

'thisStringIsAwesomeInnit'

In [ ]:
'm' in my_string

True

In [ ]:
my_string[3]


's'

In [ ]:
my_string[4:9]

'Strin'

In [ ]:
my_string.upper()

'THISSTRINGISAWESOME'

In [ ]:
my_string.lower()


'thisstringisawesome'

In [ ]:
my_string.count('w')

1

In [ ]:
my_string.replace('e','i')

'thisStringIsAwisomi'

In [ ]:
my_string.strip()

'thisStringIsAwesome'

In [ ]:
a = 'is'
b = 'nice'
my_list = ['my','list',a,b]
my_list2 = [[4,5,6,7],[3,4,5,6]]

In [ ]:
my_list[1]

'list'

In [ ]:
my_list[-3]

'list'

In [ ]:
my_list[1:3]

['list', 'is']

In [ ]:
my_list[1:]

['list', 'is', 'nice']

In [ ]:
my_list[:3]

['my', 'list', 'is']

In [ ]:
my_list[:]

['my', 'list', 'is', 'nice']

In [ ]:
my_list2[1][0]

3

In [ ]:
my_list2[1][:2]

[3, 4]

In [ ]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
my_list > 4

TypeError: ignored

In [ ]:
my_list.index(a)

2

In [ ]:
my_list.count(a)

1

In [ ]:
my_list.append('!')
print(my_list)

['my', 'list', 'is', 'nice', '!']


In [ ]:
my_list.remove('!')
print(my_list)

['my', 'list', 'is', 'nice']


In [ ]:
del(my_list[0:1])
print(my_list)

['list', 'is', 'nice']


In [ ]:
my_list.reverse()
print(my_list)

['nice', 'is', 'list']


In [ ]:
my_list.extend('!')
print(my_list)

['nice', 'is', 'list', '!']


In [ ]:
my_list.pop(-1)

'!'

In [ ]:
my_list.insert(0,'!')
print(my_list)

['!', 'nice', 'is', 'list']


In [ ]:
my_list.sort()
print(my_list)

['!', 'is', 'list', 'nice']


In [ ]:
import numpy
import numpy as np
from math import  pi

In [ ]:
my_list = [1,2,3,4]
my_array = np.array(my_list)
my_2darray = np.array([[1,2,3],[4,5,6]])

In [ ]:
my_array[1]

2

In [ ]:
my_array[0:2]

array([1, 2])

In [ ]:
my_2darray[:,0]

array([1, 4])

In [ ]:
my_array > 3

array([False, False, False,  True])

In [ ]:
my_array * 2

array([2, 4, 6, 8])

In [ ]:
my_array + np.array([5,6,7,8])

array([ 6,  8, 10, 12])

In [ ]:
my_array.shape

(4,)

In [ ]:
np.append(other_array)

NameError: ignored

In [ ]:
np.insert(my_array,1,5)

array([1, 5, 2, 3, 4])

In [ ]:
np.delete(my_array,[1])

array([1, 3, 4])

In [ ]:
np.mean(my_array)

2.5

In [ ]:
np.median(my_array)

2.5

In [ ]:
my_array.corrcef()

AttributeError: ignored

In [ ]:
np.std(my_array)

1.118033988749895